version: '3'

services:
    python:
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - .:/Todo_app
        ports:
            - 8000:8000
      
     


